name: Rust

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: make test
    - name: Clippy 
      run: make clippy
    - name: Format
      run: make fmt
